name: find_track_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  http:
  record:
  flutter:
    sdk: flutter
  provider:
  equatable:
  flutter_svg:
  flutter_bloc:
  avatar_glow:
  url_launcher:
  firebase_auth:
  firebase_core:
  flutterfire_ui:
  path_provider:
  flutter_dotenv:
  cloud_firestore:
  firebase_storage:
  cupertino_icons:
  permission_handler:
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/musicApp.png"
#   min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/FindTrackAppLogo.png
    - assets/images/SongImg.png
    - assets/images/apple.svg
    - assets/images/podcast-solid.svg
    - assets/images/spotify.svg
    - assets/images/musicApp.png
    - .env
